# Generated by Django 5.2.4 on 2025-10-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('extracto', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, upload_to='paginas/')),
                ('fecha_publicacion', models.DateField()),
                ('destacada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['-fecha_publicacion', '-creado'],
            },
        ),
    ]
