# Generated by Django 5.2.4 on 2025-10-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
